config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }, path_names: { edit: 'settings' }
  root 'pages#index'
  resources :books, only: %i[index show]
  resource :address, only: [:update]
  resources :reviews, only: [:create]
  resource :cart, only: %i[show update]
  resource :checkout, only: %i[show update]
  resource :quick_registration, only: %i[show create]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  decorates_assigned :cart

  def show
    @cart = current_cart.decorate
  end

  def update
    service = Cart::UpdateCartService.call(order: current_cart, order_params: cart_params)
    if service.success?
      flash[:success] = service.success_message
    else
      flash[:danger] = service.errors_message
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def cart_params
    params.require(:order).permit(coupon: :code, order_item: %i[quantity book_id destroy_id])
  end
end

app/views/carts/partials/_order_items.html.haml
%tr
  %td
    - if order_item.book.title_image.attached?
      = link_to book_path(id: order_item.book) do
        .general-img-wrap-table
          %img.cart-img-shadow.pull-left{src: url_for(order_item.book.title_image), alt: "design-book"}
  %td
    = link_to book_path(id: order_item.book) do
      %p.title= order_item.book.title
  %td
    %span.font-16.in-gold-500= number_to_currency(order_item.book.price)
  %td
    .input-group
      = button_to cart_path(order: { order_item: { book_id: order_item.book, quantity: -1 }}), method: :put, class: 'input-link', style: "border:none;" do
        %i.fa.fa-minus.line-heaght-40
      %input.form-control.quantity-input{type: "text", value: order_item.quantity}
      = button_to cart_path(order: { order_item: { book_id: order_item.book, quantity: 1 }}), method: :put,  class: 'input-link', style: "border:none;" do
        %i.fa.fa-plus.line-heaght-40
  %td
    %span.font-16.in-gold-500= number_to_currency(order_item.subtotal)
  %td
    = link_to cart_path(order: { order_item: { destroy_id: order_item }}), method: :put, class: 'button close general-cart-close' do
      %span{'aria-hidden': "true"} &times;