config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }, path_names: { edit: 'settings' }
  root 'pages#index'
  resources :books, only: %i[index show]
  resource :address, only: [:update]
  resources :reviews, only: [:create]
  resource :cart, only: %i[show update]
  resource :checkout, only: %i[show update]
  resource :quick_registration, only: %i[show create]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
  enum address_type: { billing: 0, shipping: 1 }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, presence: true

  has_many :author_books, dependent: :destroy
  has_many :books, through: :author_books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  MIN_PRICE = 0.0

  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books
  belongs_to :category

  has_many :reviews, dependent: :destroy

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  has_one_attached :title_image, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :title, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: MIN_PRICE }
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :books, dependent: :destroy, counter_cache: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  SALE_RANGE = { min: 0.0, max: 1.0 }.freeze

  belongs_to :order, optional: true

  validates :sale, :code, presence: true
  validates :sale, numericality: { greater_than_or_equal_to: SALE_RANGE[:min] }
  validates :sale, numericality: { less_than_or_equal_to: SALE_RANGE[:max] }
end

app/models/delivery_type.rb
class DeliveryType < ApplicationRecord
  has_many :order_delivery_type, dependent: :destroy
  has_many :orders, through: :order_delivery_type
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :user, optional: true

  has_many :order_items, dependent: :destroy
  has_many :books, through: :order_items

  has_one :coupon, dependent: :destroy

  has_one :billing_address, -> { billing },
          inverse_of: :addressable, as: :addressable, class_name: 'Address', dependent: :destroy
  has_one :shipping_address, -> { shipping },
          inverse_of: :addressable, as: :addressable, class_name: 'Address', dependent: :destroy

  has_one :order_delivery_type, dependent: :destroy
  has_one :delivery_type, through: :order_delivery_type
  has_one :card, dependent: :destroy

  enum status: { address: 0, delivery: 1, payment: 2, confirm: 3, checkout_complete: 4,
                 in_delivery: 5, delivered: 6, canceled: 7 }

  scope :in_progress, -> { where(status: %i[address delivery payment confirm checkout_complete in_delivery]) }
  scope :in_queue, -> { where(status: :checkout_complete) }
  scope :in_delivery, -> { where(status: :in_delivery) }
  scope :delivered, -> { where(status: :delivered) }
  scope :canceled, -> { where(status: :canceled) }
  scope :checkout_finished, -> { where(status: %i[checkout_complete in_delivery delivered canceled]) }

  aasm column: :status, enum: true do
    state :address, initial: true
    state :delivery, :payment, :confirm, :checkout_complete,
          :in_delivery, :delivered, :canceled

    event(:delivery_step) { transitions from: :address, to: :delivery }
    event(:payment_step) { transitions from: :delivery, to: :payment }
    event(:confirm_step) { transitions from: :payment, to: :confirm }
    event(:complete_step) { transitions from: :confirm, to: :checkout_complete }
    event(:in_delivery_step) { transitions from: :checkout_complete, to: :in_delivery }
    event(:delivered_step) { transitions from: :in_delivery, to: :delivered }
    event(:canceled_step) { transitions from: %i[checkout_complete in_delivery delivered], to: :canceled }
  end
end

app/models/order_delivery_type.rb
class OrderDeliveryType < ApplicationRecord
  belongs_to :order
  belongs_to :delivery_type
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  validates_with OrderItemValidator

  MIN_QUANTITY = 1

  belongs_to :book
  belongs_to :order

  validates :quantity, numericality: { greater_than_or_equal_to: MIN_QUANTITY, message: I18n.t('cart.low_quantity') }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: { unprocessed: 0, approved: 1, rejected: 2 }

  scope :processed, -> { where(status: %i[approved rejected]) }
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_FORMAT = /\A(?=.{8,}\z)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*\z/.freeze

  has_one :billing_address, -> { billing },
          inverse_of: :addressable, as: :addressable, class_name: 'Address', dependent: :destroy
  has_one :shipping_address, -> { shipping },
          inverse_of: :addressable, as: :addressable, class_name: 'Address', dependent: :destroy

  has_many :reviews, dependent: :destroy

  has_many :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:google_oauth2]

  validates :password, format: { with: PASSWORD_FORMAT }, if: :password_required?
  validates :email, presence: true

  def self.from_omniauth(access_token)
    user = User.where(email: access_token.info.email).first

    user ||= User.create(email: access_token.info.email,
                         password: Devise.friendly_token[0, 20])
    user.uid = access_token.uid
    user.provider = access_token.provider
    user.skip_confirmation!
    user.save

    user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  decorates_assigned :book, :books

  def show
    @book = Book.find(params[:id])
  end

  def index
    @pagy, @books = pagy(SortBooks.new(params).call, items: 12)
    @filters = SortBooks::BOOK_FILTERS
    @books_count = Book.all.count
    @categories = Category.all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  decorates_assigned :cart

  def show
    @cart = current_cart.decorate
  end

  def update
    service = Cart::UpdateCartService.call(order: current_cart, order_params: cart_params)
    if service.success?
      flash[:success] = service.success_message
    else
      flash[:danger] = service.errors_message
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def cart_params
    params.require(:order).permit(coupon: :code, order_item: %i[quantity book_id destroy_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  LATEST_BOOKS_AMOUNT = 3

  decorates_assigned :latest_books

  def index
    @latest_books = Book.last(LATEST_BOOKS_AMOUNT)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  def create
    review_form = ReviewForm.new(review_params)
    authorize review_form, policy_class: ReviewPolicy
    if review_form.save(current_user)
      flash[:success] = I18n.t('review.success')
    else
      flash[:danger] = review_form.errors.full_messages.to_sentence
    end
    redirect_to book_url(id: review_params[:book_id])
  end

  private

  def review_params
    params.require(:review).permit(:title, :book_rate, :body, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BookStore
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = render  'partials/header'
    = render 'partials/flash_message', cached: true
    = yield
    = render  'partials/footer'

app/views/pages/partials/_best_sellers.haml
.mb-35
  %h3= t('Best Sellers')
  .row
  - 4.times do
    .col-xs-6.col-sm-3
      .general-thumb-wrap
        .thumbnail.general-thumbnail
          %img.img-shadow.general-thumbnail-img{src:  image_url("sample_book.jpg"), alt: "design-book"}
          .thumb-hover
            .general-thumb-link-wrap
              %a.thumb-hover-link{href: "#"}
                %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
              %a.thumb-hover-link{href: "#"}
                %i.fa.fa-shopping-cart.thumb-icon
      .mb-35
        .clearfix
          %p.pull-right.font-16.in-gold-500 €00.00
          %p.title.mr-55 Android Programming for Beginners
        %span.divider-sm
        %p.lead.small John Horton

app/views/pages/partials/_latest_books.haml
#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators
    - latest_books.count.times do |index|
      %li{'class': "#{'active' if index.zero?}", 'data-target': "#slider", 'data-slide-to': "#{index}"}
  .carousel-inner{role: "listbox"}
    - latest_books.each_with_index do |book, index|
      .item.carousel-item{'class': "#{'active' if index.zero?}"}
        .row
          .col-sm-5
            .general-img-wrap
              %img.img-shadow.general-thumbnail-img{src: url_for(book.title_image), alt: "design-book"}
          .col-sm-7
            .mb-60
              %h1.book_name
                = book.title
              %p.lead
                = book.description
              %p.lead.small
                = book.authors_names
              .general-align
                = link_to t('home.buy_now'), cart_path(order: { order_item: { book_id: book.id, quantity: 1 } }), method: :put, class: 'button btn btn-primary'
  %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{'aria-hidden': "true"}
    %span.sr-only Previous
  %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{'aria-hidden': "true"}
    %span.sr-only Next

app/views/partials/_flash_message.haml
.flash.text-center
  - flash.each do |message_type, message|
    %div{ class: "alert alert-#{message_type}" }
      = message

app/views/partials/_footer.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to  'Home', root_path, class: 'a'
          %li
            %a.nav-link{href: "#"} Shop
          %li
            %a.nav-link{href: "#"} Orders
          %li
            %a.nav-link{href: "#"} Settings
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/partials/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
      = link_to t('layout.title'), root_path, class: 'navbar-brand'
    %a.shop-link.pull-right.hidden-xs{href: cart_path}
      -if user_signed_in? || session[:cart_id]
        %span.shop-icon
          %span.shop-quantity= cart_items_count
      - else 
        %span.shop-icon
          %span.shop-quantity= 0
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to  'Home', root_path, class: 'a'
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= t('layout.shop')
            %ul.dropdown-menu
              %li
                = link_to t('catalog.all'), books_path
              - Category.all.each do |category|
                %li
                  = link_to category.name, books_path(category_id: category)
          - if user_signed_in?
            %li
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
                = t('devise.my_account')
              %ul.dropdown-menu
                %li= link_to t('layout.settings'), edit_user_registration_path
                %li.divider{role: "separator"}
                %li= link_to t('devise.log_out'), destroy_user_session_path, method: :delete
          - else
            %li
              = link_to t('devise.log_in'), new_user_session_path
            %li
              = link_to t('devise.sign_up'), new_user_registration_path