config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }, path_names: { edit: 'settings' }
  root 'pages#index'
  resources :books, only: %i[index show]
  resource :address, only: [:update]
  resources :reviews, only: [:create]
  resource :cart, only: %i[show update]
  resource :checkout, only: %i[show update]
  resource :quick_registration, only: %i[show create]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  decorates_assigned :cart

  def show
    @cart = current_cart.decorate
  end

  def update
    service = Cart::UpdateCartService.call(order: current_cart, order_params: cart_params)
    if service.success?
      flash[:success] = service.success_message
    else
      flash[:danger] = service.errors_message
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def cart_params
    params.require(:order).permit(coupon: :code, order_item: %i[quantity book_id destroy_id])
  end
end

app/views/carts/show.html.haml
%main.container
  - if cart&.order_items.present?
    %h1.general-title-margin= t('cart.cart')
    %table.table.table-hover
      %tr.no-hover
        %th.col-pic.pl-0
          %span.in-grey-600= t('cart.product')
        %th.col-title
        %th.col-price
          %span.in-grey-600= t('cart.price')
        %th.col-quantity
          %span.in-grey-600= t('cart.quantity')
        %th.col-total
          %span.in-grey-600= t('cart.subtotal')
        %th.col-close
      = render partial: 'carts/partials/order_items', collection: cart.order_items, as: :order_item
    .general-order-wrap
      .row
        .col-sm-4
          .input-group.general-input-group
            %label.input-label= t('cart.enter_coupon_code')
            = simple_form_for 'order[coupon]', url: cart_path, method: :put do |f|
              = f.text_field :code, placeholder: t('cart.enter_coupon_code'), class: 'form-control mb-30'
              = f.button :submit, t('button.apply_coupon'), class: 'btn btn-primary mr-5 mb-15'
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18= t('cart.order_summary')
            %table.general-summary-table.general-summary-table-right.general-text-right
              %tr
                %td
                  %p.font-16 #{t('cart.subtotal')}:
                %td
                  %p.font-16= number_to_currency(cart.order_items_subtotal)
              %tr
                %td
                  %p.font-16 #{t('cart.coupon')}:
                %td
                  %p.font-16= number_to_currency(cart.order_discount)
              %tr
                %td
                  %strong.font-18 #{t('cart.order_total')}:
                %td
                  %strong.font-18= number_to_currency(cart.order_total)
    .text-center
      = link_to t('button.checkout'), current_user.present? ? checkout_path(order: cart) : quick_registration_path, method: :get, class: 'btn btn-default mb-20'
  - else
    .jumbotron.text-center.mb-0.mb-res-50
      %p= t('cart.cart_is_empty')