config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }, path_names: { edit: 'settings' }
  root 'pages#index'
  resources :books, only: %i[index show]
  resource :address, only: [:update]
  resources :reviews, only: [:create]
  resource :cart, only: %i[show update]
  resource :checkout, only: %i[show update]
  resource :quick_registration, only: %i[show create]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  def create
    review_form = ReviewForm.new(review_params)
    authorize review_form, policy_class: ReviewPolicy
    if review_form.save(current_user)
      flash[:success] = I18n.t('review.success')
    else
      flash[:danger] = review_form.errors.full_messages.to_sentence
    end
    redirect_to book_url(id: review_params[:book_id])
  end

  private

  def review_params
    params.require(:review).permit(:title, :book_rate, :body, :book_id)
  end
end

app/views/reviews/partials/_form.html.haml
= simple_form_for review, as: :review, url: reviews_path, html: { class: 'row' }, defaults: { input_html: { class: "form-control" }} do |f|
  %h3= t('reviews.write_a_review')
  %p.general-info-text= t('reviews.score')
  .mb-15{data: { controller: 'review'} }
    - (1..5).each do |index|
      %i.fa.fa-star.rate-star.rate-empty{'data-value': index,'data-review-target': 'stars','data-action': 'mouseover->review#addStar mouseout->review#removeStar click->review#setStar'}
    = f.hidden_field :book_rate, as: :hidden, value: '0'
  = f.hidden_field :book_id, value: book_id
  .col-md-8
    .mb-40
      = f.input :title, required: false
      = f.input :body, as: :text, required: false
    .text-right
      = f.button :submit, t('button.post'), class: 'btn btn-default pull-right general-position'